# Model arguments
model_name_or_path: AmberYifan/Qwen2.5-7B-sft-ultrachat  # glorgao/Qwen2.5-7B-SFT
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
# For definitions, see: src/h4/training/config.py
chat_template: "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
gamma_beta_ratio: 0.8
do_eval: true
evaluation_strategy: steps
eval_steps: 1000
gradient_accumulation_steps: 4
per_device_train_batch_size: 5 
per_device_eval_batch_size: 5
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: jlpang888/qwen-2.5-7b-simpo-full # hub_model_id is used for querying the csv file, i.e., the curriculum.
learning_rate: 8.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: /mnt/data1/jinlong/CL_DPO_outputs/qwen-2.5-7b-simpo-full/
run_name: qwen-2.5-7b-simpo-full
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
seed: 42
warmup_ratio: 0.1