# Model arguments
model_name_or_path: /mnt/data1/jinlong/DPO-noisy-outputs/llama-3-1b-sft #/mnt/data1/jinlong/DPO-noisy-outputs/llama-3-1b-sft
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# # LoRA arguments
use_peft: true
load_in_8bit: false
load_in_4bit: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj


# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
  # argilla/ultrafeedback-binarized-preferences-cleaned: 0.01
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 0.01
label_smoothing: 0.0
loss_type: sigmoid ##dpo
# gamma_beta_ratio: 0.5
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 8 #8
per_device_train_batch_size: 6
per_device_eval_batch_size: 6
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: jlpang888/llama-3-1b-base-dpo-lora
learning_rate: 5.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: /mnt/data1/jinlong/DPO-noisy-outputs/llama-3-1b-dpo-test/
# do_merge_model: true
# merged_model_output_dir: /mnt/data1/jinlong/DPO-noisy-outputs/llama-3-1b-dpo-merged/
run_name: llama-3-1b-base-dpo-lora
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
