# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# # LoRA arguments
use_peft: true
# load_in_8bit: true
# load_in_4bit: true
lora_r: 128
lora_alpha: 64
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj



# Data training arguments
dataset_mixer:
  # HuggingFaceH4/ultrafeedback_binarized: 1.0
  /home/jlpang/QualityDPO/datasets/ultrafeedback: 1.0

dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 0.01
# gamma_beta_ratio: 0.8
label_smoothing: 0.0
loss_type: sigmoid ##dpo
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 2
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: jlpang888/mistral-7b-base-dpo-new-lora
learning_rate: 3.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: /mnt/data1/jinlong/DPO-noisy-outputs/mistral-7b-dpo-new/
run_name: mistral-7b-base-dpo-new-lora
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
