# Model arguments
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# # LoRA arguments
use_peft: false
# load_in_8bit: true
# load_in_4bit: true
lora_r: 128
lora_alpha: 64
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj



# Data training arguments
dataset_mixer:
  # HuggingFaceH4/ultrafeedback_binarized: 1.0
  # /home/jlpang/QualityDPO/datasets/ultrafeedback: 1.0
  # jlpang888/ultrafeedback_sorted_score_diff: 1.0
  jlpang888/mistral-instruct-ultrafeedback_sorted_rating_score: 1.0

dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 0.01
# gamma_beta_ratio: 0.8
label_smoothing: 0.0
loss_type: noisy-tolerant-4-6-instruct ##dpo
do_eval: false
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 2
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: jlpang888/mistral-7b-instruct-mix-dpo-lr4
learning_rate: 8.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: ./CL_DPO_outputs/mistral-7b-instruct-mix-dpo-lr4/
run_name: mistral-7b-instruct-mix-dpo-lr4
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
