# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B #meta-llama/Meta-Llama-3-8B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2


# LoRA arguments
use_peft: false
# load_in_8bit: false
# load_in_4bit: true
lora_r: 128
lora_alpha: 64
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj


# Data training arguments
chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
dataset_mixer:
  # sahandrez/ultrafeedback_kto: 1.0
  jlpang888/ultrafeedback_kto_sft: 0.001
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 1
per_device_eval_batch_size: 5
per_device_train_batch_size: 5 ###1B: 8; 3B: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 2.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 512
max_steps: -1
num_train_epochs: 1
output_dir: /mnt/data1/jinlong/DPO-noisy-outputs/llama-3-8b-sft-kto/
run_name: llama-3-8b-sft-kto
overwrite_output_dir: true
hub_model_id: llama-3-8b-sft-kto
hub_strategy: every_save
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 1000000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1